server:
  port: 8098
  servlet:
    context-path:

spring:
  application:
    name: job-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/silence-platform?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: admin123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      pool-name: silence_job
      max-lifetime: 1800000
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
  mail:
    host: smtp.163.com
    port: 465
    protocol: smtps
    username: 13611988536@163.com
    password: PTsXDSWS8PqZarUA
    from: 13611988536@163.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory: javax.net.ssl.SSLSocketFactory
mybatis-plus:
  configuration:
    # 开启驼峰命名映射
    map-underscore-to-camel-case: true
    # 日志输出 SQL
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.old.silence.data.commons.handler.GenericEnumTypeHandler
  global-config:
    db-config:
      # 全局主键类型（可选）
      id-type: auto
      # 逻辑删除字段（可选）
      logic-delete-field: is_deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  type-handlers-package: com.old.silence.data.commons.handler



silence-job:
  retry-pull-page-size: 1000 # 拉取重试数据的每批次的大小
  job-pull-page-size: 1000 # 拉取重试数据的每批次的大小
  server-port: 17888  # 服务器端口
  log-storage: 7 # 日志保存时间(单位: day)
  rpc-type: grpc

threadpool:
  config:
    coreSize: 10
    maxSize: 10
    keepAliveTime: 3000
    queueSize: 5000

platform:
  system:
    identifier: JC


silence:
  auth:
    center:
      security:
        api:
          white-list: